-- Packer
require('plugins')

-- Utils
require('utils.remaps')

-- Config
require('settings')
require('settings.color')
require('settings.completion')
require('settings.filetype')
require('settings.font')
require('settings.keymap')
require('settings.netrw')

-- LSP Config
require('lsp')

-- Plugins config
require('plugins.diffview')
require('plugins.ctrlsf')
require('plugins.editorconfig')
require('plugins.feline')
require('plugins.formatter')
require('plugins.fterm')
require('plugins.gitblame')
require('plugins.gitsigns')
require('plugins.hlslens')
require('plugins.indent-blankline')
-- require('plugins.indent-guides')
require('plugins.kommentary')
-- require('plugins.lightspeed')
require('plugins.lspinstall')
require('plugins.lspkind')
-- require('plugins.minimap')
require('plugins.neoscroll')
require('plugins.numb')
require('plugins.nvim-autopairs')
require('plugins.nvim-reload')
require('plugins.nvim-ts-rainbow')
require('plugins.nvimtree')
require('plugins.sidebar')
require('plugins.sideways')
require('plugins.splitjoin')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.todo-comments')
require('plugins.vim-fugitive')
-- require('plugins.vim-gutentags')
require('plugins.vim-rooter')
require('plugins.vim-rubocop')
require('plugins.vim-signature')
require('plugins.vim-startify')
