return {
  mode = { "n", "v" },
  e = {
    name = "[File] Explorer",
    f = { ":Neotree toggle float<CR>", "Float File Explorer" },
    l = { ":Neotree toggle left<CR>", "Left File Explorer" },
    r = { ":Neotree toggle right<CR>", "Right File Explorer" },
  },
  s = {
    name = "Search",
    f = { ":Telescope find_files<cr>", "Find File (CWD)" },
    h = { ":Telescope help_tags<cr>", "Find Help" },
    H = { ":Telescope highlights<cr>", "Find highlight groups" },
    M = { ":Telescope man_pages<cr>", "Man Pages" },
    o = { ":Telescope oldfiles<cr>", "Open Recent File" },
    R = { ":Telescope registers<cr>", "Registers" },
    t = { ":Telescope live_grep<cr>", "Live Grep" },
    T = { ":Telescope grep_string<cr>", "Grep String" },
    k = { ":Telescope keymaps<cr>", "Keymaps" },
    C = { ":Telescope commands<cr>", "Commands" },
    l = { ":Telescope resume<cr>", "Resume last search" },
    c = { ":Telescope git_commits<cr>", "Git commits" },
    B = { ":Telescope git_branches<cr>", "Git branches" },
    m = { ":Telescope git_status<cr>", "Git status" },
    S = { ":Telescope git_stash<cr>", "Git stash" },
    z = { ":Telescope zoxide list<cr>", "Zoxide" },
    e = { ":Telescope frecency<cr>", "Frecency" },
    b = { ":Telescope buffers<cr>", "Buffers" },
    p = { ":AerialToggle!<cr>", "Areal Toggle" },
    d = {
      name = "+DAP",
      c = { ":Telescope dap commands<cr>", "Dap Commands" },
      b = { ":Telescope dap list_breakpoints<cr>", "Dap Breakpoints" },
      g = { ":Telescope dap configurations<cr>", "Dap Configurations" },
      v = { ":Telescope dap variables<cr>", "Dap Variables" },
      f = { ":Telescope dap frames<cr>", "Dap Frames" },
    },
  },
}
